### PR TITLE
Added function pointer comparison to FunctionPointerBase.

### PR DESCRIPTION
**Pull request by marcuschangarm**
See https://github.com/ARMmbed/core-util/pull/24

### CODE REVIEW

**Comment by bremoran** [comment]
I still don't like your memset, but otherwise, +1

**Comment by marcuschangarm** [comment]
The memset is there to keep the memcpy in line 74 company! :p

**Comment by bremoran** [comment]
I never said the memcpy shouldn't die too!

**Comment by 0xc0170** [comment]
We got general +1 , and those standard calls can be patched

**Pull request merged**
