### PR TITLE
Module - update mbed drivers dep

### PR DESCRIPTION
**Pull request by 0xc0170**
If this module gets new major version, we will need to update ualloc, minar. I am not owner to those 2.

### CODE REVIEW

**Comment by bogdanm** [comment]
+1
This will result in a new minor update on core-util

**Comment by 0xc0170** [comment]
Let's do a minor bump

cc @autopulated

**Comment by autopulated** [comment]
:thumbsup:

To explain the reasoning for the minor bump (not major) here, despite the technically breaking change of including C++11 code in some public headers in mbed-drivers:

If your application ​*only*​ has a dependency on core-util, then it won't really be using mbed OS, any application that's actually using mbed-os will have some other dependency on mbed-drivers (since the only reason core-util has a dependency on mbed-drivres is to implement assert), and will almost certainly not be compiled for an mbed OS target.

Further, the declaration of the mbed_die function used to implement assert hasn't changed (and the `mbed-drivers/mbed_interface.h` header file used to declare it, doesn't pull in anything else that's changed in a breaking way), so there's no way that the breaking change in mbed-drivers can actually affect a user who only uses mbed-drivers via this module.

If `mbed_interface.h` were to subsequently include c++11 code, the question of a version bump here would have to be revisited (even in that case it might be possible to compile only a part of this module internally as C++11, as the mbed_interface include is not itself in a public header of this module.

**Comment by bogdanm** [comment]
Published version 1.2.0

**Pull request merged**
