### PR TITLE
moving Event.h, FunctionPointer*.h, and mbed-sbrk into core-utils; moved out of m…

### PR DESCRIPTION
**Pull request by rgrover**
…bed-drivers

corresponds with https://github.com/ARMmbed/mbed-drivers/pull/85
This is a first step towards having a POSIX platform.
@bogdanm @0xc0170 @bremoran

### CODE REVIEW

**Comment by 0xc0170** [comment]
+1

When we move things like in this PR, the issues related to those files, shall we transfer them ?

**Comment by bogdanm** [comment]
+1 from me too. We have to be careful abour versioning this and the corresponding changes in other repos. And sure, we can transfer the issues.

**Comment by 0xc0170** [comment]
We are not yet in 1.x.x, thus this will be version bump minor?

**Comment by bogdanm** [comment]
Yup, a minor should do the trick I think.
One more thing that I've just noticed: `FunctionPointer` and friends are in their previous `mbed` namespace, while the classes in `core-util` are in the `mbed::util` namespace. We should probably rename that completely to `core::util`, but for now would you please move the relevant classes to `mbed::util`? Thanks.

**Comment by rgrover** [comment]
please hold back on the merge to allow me time to move the sbrk family into core-util. @bremoran

**Comment by rgrover** [comment]
The move of mbed-sbrk into core-util is ready for review 
@bogdanm @bremoran @0xc0170

**Comment by 0xc0170** [comment]
LGTM

**Comment by bogdanm** [comment]
Looks good!

**Pull request merged**
