### PR TITLE
remove un-necessary include of core_generic.h from PoolAllocator.cpp

### PR DESCRIPTION
**Pull request by rgrover**
@0xc0170 @bogdanm

### CODE REVIEW

**Comment by bogdanm** [comment]
+1

**Comment by 0xc0170** [comment]
+1

**Comment by rgrover** [comment]
bump 
@0xc0170 @bogdanm

**Comment by rgrover** [comment]
Guys, i need to push through a bunch of small but unrelated commits leading to the support of Posix backend for minar. I'd like to submit one coherent pull request at a time. Could you please help this process by speeding up the reviews and merge? thanks.

**Comment by rgrover** [comment]
perhaps I should just submit multiple pull requests to reduce the administrative overheads around merging and publishing.

**Comment by bogdanm** [comment]
It depends on the type of change. If the set of your PRs leaves some repositories in an un-compilable state until all PRs are merged, it's better to make this clear by specifying the complete list of PRs in the set. If the PRs don't make the code uncompilable (like this one), it's OK to create them one by one (but keep an eye on versioning). I'll merge this PR and update the minor version of the module.

**Comment by bogdanm** [comment]
Done. Sorry for taking so long on this.

**Pull request merged**
